// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVVZsav2ui-EblCWmohxFaXtIEU8WBUQk',
    appId: '1:92035119165:web:89877c04401f7548f3d254',
    messagingSenderId: '92035119165',
    projectId: 'bus-iraq',
    authDomain: 'bus-iraq.firebaseapp.com',
    storageBucket: 'bus-iraq.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT3-h6VXBloJrW335xEx7GXG-GjZbBLJ4',
    appId: '1:92035119165:android:a7afbbffb6eff260f3d254',
    messagingSenderId: '92035119165',
    projectId: 'bus-iraq',
    storageBucket: 'bus-iraq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF-bNDQd-H2Ggho1-9ngj9ZYiuAnlx9U4',
    appId: '1:92035119165:ios:9710b1f2929344d8f3d254',
    messagingSenderId: '92035119165',
    projectId: 'bus-iraq',
    storageBucket: 'bus-iraq.appspot.com',
    iosBundleId: 'com.busiraq.busIraq2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF-bNDQd-H2Ggho1-9ngj9ZYiuAnlx9U4',
    appId: '1:92035119165:ios:cc602ebb5e9254adf3d254',
    messagingSenderId: '92035119165',
    projectId: 'bus-iraq',
    storageBucket: 'bus-iraq.appspot.com',
    iosBundleId: 'com.busiraq.busIraq2.RunnerTests',
  );
}
